FROM python:3.6.0-alpine

ENV APP_HOME /app
ENV POST_DATABASE_HOST post_db
ENV POST_DATABASE posts

WORKDIR $APP_HOME
ADD . $APP_HOME

RUN apk update \
    && apk add --no-cache gcc musl-dev \
    && pip install -r /app/requirements.txt

ENTRYPOINT ["python3", "post_app.py"]
