version: '3'
services:
  zipkin:
    image: openzipkin/zipkin:${ZIPKIN_VER}
    networks:
      - front_net
      - back_net
    ports:
      - "9411:9411"

  fluentd:
    image: ${USERNAME}/fluentd:${FLUENTD_VER}
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:${ELASTIC_VER}
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:${KIBANA_VER}
    ports:
      - "5601:5601"

networks:
  back_net:
  front_net:
