version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd:${FLUENTD_VER}
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:${ELASTIC_VER}
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:${KIBANA_VER}
    ports:
      - "5601:5601"
