groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'
    - alert: UI service requests slowdown
      expr: histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le)) > 0.08
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has exceeded threshold (0.08) of 95% quantile for more than 1 minute'
        summary: '95% quantile threshold exceeded for {{ $labels.instance }}'
