version: '3.3'
services:
  ui:
    command: "puma --debug -w 2"
    volumes:
      - /home/docker-user/ui:/app
  post:
    volumes:
      - /home/docker-user/post-py:/app
  comment:
    command: "puma --debug -w 2"
    volumes:
      - /home/docker-user/comment:/app
